https://www.perplexity.ai/search/94f7fc8c-0595-416f-b080-1e318bd7404d

In [ ]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data

In [ ]:
data['a']

In [ ]:
data['a'][2]

In [ ]:
data['a':'b']

In [ ]:
#Series->堆疊資料>(long data)
#2維資料->非堆疊資料>(width data)
data.unstack().stack()

使用unstack()時,(組合)索引不可以重複

In [ ]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(10),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd','a'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3,1]])
#索引(a,1)重複了,無法做unstack
data.unstack()

In [3]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(10),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd','a'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3,1]])
#索引(a,1)重複了,無法做unstack
#必需先groupby完後,才可以unstack
data.index.names = ['key1','key2']
data1 = data.groupby(level=['key1','key2']).sum()
data1.unstack()

key2         1         2         3
key1
a     0.927373  1.378951 -0.760062
b     0.734699  0.077080       NaN
c     0.399234       NaN  0.320097
d          NaN -0.427116  0.110800

In [4]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1','key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [5]:
series1 = frame.stack(level=['縣市','顏色'],future_stack=True)
series1.unstack(level=['key1', '縣市'])

key1          a          b
縣市           台北   台中    台北    台中
key2 顏色
1    Green  0.0  2.0   6.0   8.0
     Red    1.0  NaN   7.0   NaN
2    Green  3.0  5.0   9.0  11.0
     Red    4.0  NaN  10.0   NaN

In [6]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1','key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [7]:
frame.T.groupby(level='顏色').sum()

key1   a      b
key2   1  2   1   2
顏色
Green  2  8  14  20
Red    1  4   7  10